import { StyleSheet, Button, Text, View } from 'react-native';

const styles = StyleSheet.create({
  headerContainer: {
    // alignItems: "center",
    backgroundColor: '#000',
    borderRadius: 12,
    // flexDirection: 'row',
    height: 48,
    // justifyContent: 'center',
    position: 'absolute',
    top: 48,
    width: 256,
    zIndex: 100,
  },
  header: {
    // alignItems: "center",
    // backgroundColor: '#000',
    flexDirection: 'row',
    // height: 64,
    justifyContent: 'center',
    // position: 'absolute',
    // top: 48,
    // width: 256,
    // zIndex: 100,
    height: 48,
  },
  headerD: {
    alignSelf: 'center',
    // borderBottomWidth: 2,
    // borderColor: 'red',
    // borderLeftWidth: 2,
    // borderRightWidth: 0,
    // borderStyle: 'solid',
    // borderTopWidth: 2,
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  headerU: {
    alignSelf: 'center',
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  headerB: {
    alignSelf: 'center',
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  headerS: {
    alignSelf: 'center',
    fontSize: 32,
    fontWeight: 'bold',
    justifyContent: 'center',
    textAlign: 'center',
    flex: 1,
  },
});

export default styles;
