import React from 'react';

import CnSvg from '../../../components/LanguageSelect/components/flags/CnSvg';
import DeSvg from '../../../components/LanguageSelect/components/flags/DeSvg';
import EnSvg from '../../../components/LanguageSelect/components/flags/EnSvg';
import EsSvg from '../../../components/LanguageSelect/components/flags/EsSvg';
import FrSvg from '../../../components/LanguageSelect/components/flags/FrSvg';
import ItSvg from '../../../components/LanguageSelect/components/flags/ItSvg';
import JpSvg from '../../../components/LanguageSelect/components/flags/JpSvg';
import PtSvg from '../../../components/LanguageSelect/components/flags/PtSvg';
import RuSvg from '../../../components/LanguageSelect/components/flags/RuSvg';

import MaSvg from '../../../components/LanguageSelect/components/flags/MaSvg';
import CzSvg from '../../../components/LanguageSelect/components/flags/CzSvg';
import CySvg from '../../../components/LanguageSelect/components/flags/CySvg';
import DkSvg from '../../../components/LanguageSelect/components/flags/DkSvg';
import IdSvg from '../../../components/LanguageSelect/components/flags/IdSvg';
import MySvg from '../../../components/LanguageSelect/components/flags/MySvg';
import UaSvg from '../../../components/LanguageSelect/components/flags/UaSvg';
import VnSvg from '../../../components/LanguageSelect/components/flags/VnSvg';
import ArSvg from '../../../components/LanguageSelect/components/flags/ArSvg';
import HuSvg from '../../../components/LanguageSelect/components/flags/HuSvg';
import KrSvg from '../../../components/LanguageSelect/components/flags/KrSvg';
import SgSvg from '../../../components/LanguageSelect/components/flags/SgSvg';
import IsSvg from '../../../components/LanguageSelect/components/flags/IsSvg';
import IlSvg from '../../../components/LanguageSelect/components/flags/IlSvg';
import HkSvg from '../../../components/LanguageSelect/components/flags/HkSvg';
import ClSvg from '../../../components/LanguageSelect/components/flags/ClSvg';
import GrSvg from '../../../components/LanguageSelect/components/flags/GrSvg';
import TrSvg from '../../../components/LanguageSelect/components/flags/TrSvg';
import ZaSvg from '../../../components/LanguageSelect/components/flags/ZaSvg';
import ChSvg from '../../../components/LanguageSelect/components/flags/ChSvg';
import BrSvg from '../../../components/LanguageSelect/components/flags/BrSvg';
import FiSvg from '../../../components/LanguageSelect/components/flags/FiSvg';
import NoSvg from '../../../components/LanguageSelect/components/flags/NoSvg';
import SeSvg from '../../../components/LanguageSelect/components/flags/SeSvg';
import CoSvg from '../../../components/LanguageSelect/components/flags/CoSvg';
import NzSvg from '../../../components/LanguageSelect/components/flags/NzSvg';
import AuSvg from '../../../components/LanguageSelect/components/flags/AuSvg';
import McSvg from '../../../components/LanguageSelect/components/flags/McSvg';
import PlSvg from '../../../components/LanguageSelect/components/flags/PlSvg';
import RoSvg from '../../../components/LanguageSelect/components/flags/RoSvg';
import IeSvg from '../../../components/LanguageSelect/components/flags/IeSvg';
import AtSvg from '../../../components/LanguageSelect/components/flags/AtSvg';
import BeSvg from '../../../components/LanguageSelect/components/flags/BeSvg';
import CaSvg from '../../../components/LanguageSelect/components/flags/CaSvg';
import NlSvg from '../../../components/LanguageSelect/components/flags/NlSvg';
import UsSvg from '../../../components/LanguageSelect/components/flags/UsSvg';

export const drawFlagComponent = (flag, height, width) => {
  switch (flag) {
    case 'Cn' : return <CnSvg height={height} width={width} />;
    case 'De' : return <DeSvg height={height} width={width} />;
    case 'Es' : return <EsSvg height={height} width={width} />;
    case 'Fr' : return <FrSvg height={height} width={width} />;
    case 'It' : return <ItSvg height={height} width={width} />;
    case 'Jp' : return <JpSvg height={height} width={width} />;
    case 'Pt' : return <PtSvg height={height} width={width} />;
    case 'Ru' : return <RuSvg height={height} width={width} />;

    case 'Ma' : return <MaSvg height={height} width={width} />;
    case 'Cz' : return <CzSvg height={height} width={width} />;
    case 'Cy' : return <CySvg height={height} width={width} />;
    case 'Dk' : return <DkSvg height={height} width={width} />;
    case 'Id' : return <IdSvg height={height} width={width} />;
    case 'My' : return <MySvg height={height} width={width} />;
    case 'Ua' : return <UaSvg height={height} width={width} />;
    case 'Vn' : return <VnSvg height={height} width={width} />;
    case 'Ar' : return <ArSvg height={height} width={width} />;
    case 'Hu' : return <HuSvg height={height} width={width} />;
    case 'Kr' : return <KrSvg height={height} width={width} />;
    case 'Sg' : return <SgSvg height={height} width={width} />;
    case 'Is' : return <IsSvg height={height} width={width} />;
    case 'Il' : return <IlSvg height={height} width={width} />;
    case 'Hk' : return <HkSvg height={height} width={width} />;
    case 'Cl' : return <ClSvg height={height} width={width} />;
    case 'Gr' : return <GrSvg height={height} width={width} />;
    case 'Tr' : return <TrSvg height={height} width={width} />;
    case 'Za' : return <ZaSvg height={height} width={width} />;
    case 'Ch' : return <ChSvg height={height} width={width} />;
    case 'Br' : return <BrSvg height={height} width={width} />;
    case 'Fi' : return <FiSvg height={height} width={width} />;
    case 'No' : return <NoSvg height={height} width={width} />;
    case 'Se' : return <SeSvg height={height} width={width} />;
    case 'Co' : return <CoSvg height={height} width={width} />;
    case 'Nz' : return <NzSvg height={height} width={width} />;
    case 'Au' : return <AuSvg height={height} width={width} />;
    case 'Mc' : return <McSvg height={height} width={width} />;
    case 'Pl' : return <PlSvg height={height} width={width} />;
    case 'Ro' : return <RoSvg height={height} width={width} />;
    case 'Ie' : return <IeSvg height={height} width={width} />;
    case 'At' : return <AtSvg height={height} width={width} />;
    case 'Be' : return <BeSvg height={height} width={width} />;
    case 'Ca' : return <CaSvg height={height} width={width} />;
    case 'Nl' : return <NlSvg height={height} width={width} />;
    case 'Us' : return <UsSvg height={height} width={width} />;

    default : return <EnSvg height={height} width={width} />;
  };
};
