import { StyleSheet, Button, Text, View } from 'react-native';

const styles = StyleSheet.create({
  options: {
    display: 'flex',
    flexDirection: 'row',
    // height: 48,
    // lineHeight: 48,
    width: '100%',
    backgroundColor: 'black',
    // borderRadius: 8,
    // borderStyle: 'solid',
    // borderWidth: 2,
    // borderColor: 'white',
    // flex: 1,
    // alignSelf: 'center',
    justifyContent: 'center',
  },
  // buttonContainer: {
  //   alignItems: 'center',
  //   flex: 1,
  //   justifyContent: 'center',
  // },
  // de: {
  //   aspectRatio: 1/1,
  //   backgroundColor: 'black',
  //   borderColor: 'white',
  //   borderRadius: 24,
  //   borderStyle: 'solid',
  //   borderWidth: 1,
  //   flex: 1,
  // },
  // en: {
  //   aspectRatio: 1/1,
  //   backgroundColor: 'black',
  //   borderColor: 'white',
  //   borderRadius: 24,
  //   borderStyle: 'solid',
  //   borderWidth: 1,
  //   flex: 1,
  // },
  // es: {
  //   aspectRatio: 1/1,
  //   backgroundColor: 'black',
  //   borderColor: 'white',
  //   borderRadius: 24,
  //   borderStyle: 'solid',
  //   borderWidth: 1,
  //   flex: 1,
  // },
  // it: {
  //   aspectRatio: 1/1,
  //   backgroundColor: 'black',
  //   borderColor: 'white',
  //   borderRadius: 24,
  //   borderStyle: 'solid',
  //   borderWidth: 1,
  //   flex: 1,
  // },
  // pt: {
  //   aspectRatio: 1/1,
  //   backgroundColor: 'black',
  //   borderColor: 'white',
  //   borderRadius: 24,
  //   borderStyle: 'solid',
  //   borderWidth: 1,
  //   flex: 1,
  // },
  // flag: {
  //   width: 46,
  //   height: 46,
  // },
});

export default styles;
